runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "2.5.2"
